### ISSUE TITLE
baseline model

### ISSUE THREAD

**Issue by cx51666666** [naoya-i/r4c#1]
Hello, thanks for sharing the dataset. Is the source code for the Baseline model CORE available?

**Comment by naoya-i** [comment]
@cx51666666 Sorry, I just noticed your comment. Thanks for your interest in the R4C corpus. I've uploaded the baseline model. Please read https://github.com/naoya-i/r4c/blob/master/README.md#baseline-models for further instruction. You can use `-m Dep` option to run the CORE baseline model.

Please do let us know when you have your own results ;)
